#!/usr/bin/env python3

from os import environ, execl, sep
from pathlib import PurePath

root = PurePath(sep)
arg0 = root / "command" / "s6-notifyoncheck"
execl(
    arg0,
    arg0,
    root / "usr" / "bin" / "Xvnc",
    environ["DISPLAY"],
    "-geometry",
    f"{environ['SCR_WIDTH']}x{environ['SCR_HEIGHT']}",
    "-SecurityTypes",
    "none",
    "-AlwaysShared",
)
