#!/usr/bin/env python3

from os import execl, sep
from pathlib import Path, PurePath
from subprocess import check_call

root = PurePath(sep)
check_call((root / "command" / "s6-svwait", Path.cwd().parent / "vncconfig"))

arg0 = root / "command" / "s6-notifyoncheck"
execl(
    arg0,
    arg0,
    root / "usr" / "bin" / "websockify",
    "localhost:6800",
    "localhost:5900",
)
