#!/usr/bin/env python3

from os import environ, sep
from pathlib import Path, PurePath
from subprocess import check_call, run

root = PurePath(sep)
check_call((root / "command" / "s6-svwait", Path.cwd().parent / "vncconfig"))

arg0 = root / "usr" / "bin" / "virt-manager"
while True:
    run((arg0, "--no-fork", "--connect", environ["VIRT_CONN"]))
