#!/usr/bin/env python3

from os import sep
from os import environ
from pathlib import PurePath
from subprocess import call
from time import sleep

while call(
    (
        PurePath(sep) / "bin" / "curl",
        "--silent",
        "--max-time",
        "1",
        "--head",
        "--",
        "localhost:" + environ.get('BROADWAY_PORT'),
    )
):
    sleep(1)
