#!/usr/bin/env python3

from os import execl, sep
from pathlib import PurePath

arg0 = PurePath(sep) / "command" / "s6-notifyoncheck"
execl(
    arg0,
    arg0,
    PurePath(sep) / "bin" / "broadwayd",
)
